stages:
  - build
  - deploy

variables:
  # Roteamento alterado para o Docker Hub (Storage Externo)
  # O nome da imagem será: seunome/sre-app:hash-do-commit
  IMAGE_TAG: $DOCKER_USER/sre-app:$CI_COMMIT_SHORT_SHA
  LATEST_TAG: $DOCKER_USER/sre-app:latest

# ==========================================
# STAGE 1: COMPILAÇÃO E EMPACOTAMENTO
# ==========================================
build_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - cd app
    - docker build -t $IMAGE_TAG -t $LATEST_TAG .
    # Empurra para a nuvem pública
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
  only:
    - main 

# ==========================================
# STAGE 2: ENTREGA CONTÍNUA (DEPLOY)
# ==========================================
deploy_vps_oracle:
  stage: deploy
  image: alpine:latest
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $VPS_USER@$VPS_IP "mkdir -p /opt/sre-app"
    - scp ./docker-compose.yml $VPS_USER@$VPS_IP:/opt/sre-app/docker-compose.yml
    
    - ssh $VPS_USER@$VPS_IP "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin"
    
    # O Pulo do Gato: Injetamos a variável DOCKER_USER no momento da execução na VPS
    # Assim o docker-compose sabe exatamente qual "pasta" procurar no Docker Hub
    - ssh $VPS_USER@$VPS_IP "cd /opt/sre-app && export DOCKER_USER=$DOCKER_USER && docker-compose pull sre-app && docker-compose up -d --no-deps sre-app"
  only:
    - main